name = "linglib"
version = "0.41.0"
defaultTargets = ["Linglib"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Linglib"
globs = ["Linglib.+"]
