baseURL = "https://hawkrobe.github.io/linglib/"
languageCode = "en-us"
title = "LEANguistics"
theme = "PaperMod"

[params]
  description = "Development log for Linglib, a Lean 4 library for formal linguistics"
  author = "Robert Hawkins"
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "LEANguistics"
  Content = "Development notes from Linglib."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/hawkrobe/linglib"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Map"
    url = "/map/"
    weight = 15
[[menu.main]]
    name = "Bibliography"
    url = "/bibliography/"
    weight = 35
  [[menu.main]]
    name = "API Docs"
    url = "/docs/"
    weight = 40

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
